blog/urls.py
from django.urls import path
from blog import views

app_name='blog'

urlpatterns=[
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_edit, name='post_edit'),
    path('draft/', views.post_draft_list, name ='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    # url(r'^search/$',views.post_search, name='post_search'),
     # url(r'^post/(?P<pk>\d+)/comment/$', views.PostDetail.add_comment_to_post, name='add_comment_to_post'),
]

dev_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
urlpatterns =[
    path('', include('blog.urls')),
    path('admin/',admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login', kwargs={'template_name':'login.html'}),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

#모델의 정의
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE,)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=200)
    text = models.TextField()
    category = models.CharField(max_length=200)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null=True)
    
    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approved_comment(self):
        return self.comments.filter(approved_comment=True)
    
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE,)
    author = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__' 모든 필드 사용시
        fields =('title','text','category')


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text','author']

# class SearchForm(forms.ModelForm):
#     class Meta:
#         model = Search
#         filed = ['word']
#     # word = forms.CharField(label='Search word')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.utils import timezone
from django.views.generic import View
from django.http import HttpResponse

from .models import Post, Comment
from .forms import PostForm, LoginForm, CommentForm


def post_list(request):
    print("post_list")
    if request.GET.get("item"):
        option= request.GET.get('fd_name')
        search_type='contains'
        filter = option + '__' + search_type
        posts = Post.objects.filter(**{filter: request.GET.get('item')}, published_date__lte = timezone.now()).order_by('-published_date')
        return render(request, 'blog/post_list.html',{'posts':posts})

    posts = Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html',{'posts':posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk) # 위의 4줄과 같은 역할
    comments = Comment.objects.filter(created_date__lte = timezone.now(), post=post).order_by('-created_date')
    
    if request.method =="POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {
            'post':post,
            'comments':comments,
            'form':form
        })

#로그인 요구를 위한 장식자
@login_required(login_url='admin:login')
def post_new(request):
    if request.method =='POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()

            return redirect('post_detail', post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form':form})

@login_required(login_url='admin:login')
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form  =  PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk = post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html',{'form':form})

def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts':posts})

def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form  = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html',{'form':form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail',pk=comment.post.pk)

    
    

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class ="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
<html>
    <head>
        <title>QQ_dev_log</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        {% load static %}
        <link rel="stylesheet" href="{% static 'blog/css/blog_frame.css'%}">
        <link rel="stylesheet" href="{% static 'blog/css/blog_header.css'%}">
        <link rel="stylesheet" href="{% static 'blog/css/blog_container.css'%}">
        <script>
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
            });
        </script>


        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
    </head>
    <body>

        <!-- <span class="glyphicon glyphicon-list" id="header_menu"></span>             -->
        <div class="wrapper">

            <!-- Sidebar -->
            <nav id="sidebar">
                    <div class="sidebar-header">
                        <h3>Q's Develop</h3>
                        <strong>QD</strong>
                    </div>
    
                    <ul class="list-unstyled components">
                        <li>
                            <a href="{% url 'blog:post_list' %}">
                                <i class="glyphicon glyphicon-home"></i>
                                Home
                            </a>
                            <a href="#">
                                <i class="glyphicon glyphicon-briefcase"></i>
                                About
                            </a>
                            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
                                <i class="glyphicon glyphicon-duplicate"></i>
                                Pages
                            </a>
                            <ul class="collapse list-unstyled" id="pageSubmenu">
                                <li><a href="#">Page 1</a></li>
                                <li><a href="#">Page 2</a></li>
                                <li><a href="#">Page 3</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-link"></i>
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-paperclip"></i>
                                FAQ
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="glyphicon glyphicon-send"></i>
                                Contact
                            </a>
                        </li>
                    </ul>
    
                    <!-- <ul class="list-unstyled CTAs">
                        <li><a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a></li>
                        <li><a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a></li>
                    </ul> -->
                </nav>
        
            <!-- Page Content -->
            <div id="content">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
            
                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <span class="glyphicon glyphicon-list"></span>
                                <!-- <span>Toggle Sidebar</span> -->
                            </button>
                        </div>
    
                        {% if user.is_authenticated %}
                        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                        <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="{% url 'logout' %}" class="top-menu"><span class="glyphicon glyphicon-log-out"></span></a>
                        <span class="userName">Hello {{ user.username }}</span>
                        
                        {% else %}
                        <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-log-in"></span></span></a>
                        {% endif %}
                        
                        <h1 id="blog-title"><a href="http://127.0.0.1:8000/">Q's Develop</a></h1>
                        

                        <div class ="search-box">

                            <form class="search-box-form" action="{% url 'blog:post_list' %}" method="get">
                                <!-- <div class='search-box'></div> -->
                                <!-- <label> 검색 </label> -->
                                <select name ='fd_name' id ="" >
                                    <option value ='title'>title</option>
                                    <option value ='text'>text</option>
                                </select>
                                <input type="text" name="item">
                                <button class='btn' type='submit'>Search</button>            
                            </form>
                        </div>
                    </div>
                </nav>

                <div class = "container">
    
                    <div class = "col-md-10">
                        {% block content%}
                        {% endblock%}
                    </div>
                
        
                </div>
            </div>
        </div> 
        
                
            

                


    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class = "glyphicon glyphicon-plus"></span></a>
        <a class="btn btn-default" href="{% url 'post_remove' pk=post.pk %}"><span class = "glyphicon glyphicon-remove"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaks }}</p>
    </div>


    <div>
        <p>Add Comment</p>
        <form method="POST" class ="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
    <hr>
    <!-- <a class="btn btn-default" href = "{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a> -->
    {% for comment in comments %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div calss="date">
                {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
            </div>
            <strong> {{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :) </p>
    {% endfor %}

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class = "post">
            <p class="date">created:{{ post.created_date | date:'d-m-Y'}}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title}} </a></h1>
            <p>{{ post.text | truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock%}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New Post</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content%}
    {% for post in posts%}
    <a class="post_link" href="{% url 'blog:post_detail' pk=post.pk %}">
        <div class ="post">
            <h1>{{ post.title }}</h1>
            <p id='date'>{{post.published_date}}</p>
            <p id='contents'>{{post.text|linebreaks}}</p>
            Comments: {{ post.approved_comment.count }}
            <p id='category' >tag : {{post.category}}</p>
        </div>
    </a>
    {% endfor%}
{% endblock %}